name: CI

on:
  merge_group:
  pull_request: { }
  workflow_dispatch: { }
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  Validate-Gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./.github/actions/setup
        with:
          encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4
  Build:
    runs-on: ubuntu-latest
    needs: [ Validate-Gradle ]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./.github/actions/setup
        with:
          encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Build
        run: ./gradlew assemble
  Danger:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    name: "Run Danger"
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Danger
        uses: danger/kotlin@92d2ac8aae985fe162c88b02d641a9fa9bac81cf # 1.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Lint:
    runs-on: ubuntu-latest
    needs: [ Build ]
    strategy:
      matrix:
        command: [ detektMain, detektTest, spotlessCheck, lint, checkSortDependencies ]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./.github/actions/setup
        with:
          encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Lint
        run: ./gradlew ${{ matrix.command }}
  Tests:
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./.github/actions/setup
        with:
          encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Run Unit Tests
        run: ./gradlew test
#      - name: Codecov
#        uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3 # v5.3.1
#        with:
#          files: ./kover-aggregate/build/reports/kover/report.xml
#          token: ${{ secrets.CODE_COV_TOKEN  }} TODO
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/reports/kover/report.xml'
